Feature/#2
30th-THE-SOPT-iOS-Part/LeeSoJin pull request #5
Opened 2022-04-21 14:19 UTC by 513sojin

## 🌱 작업한 내용

`기본과제`
 - [ ] 오토 레이아웃 설정
 - [ ] 피그마에 있는 에셋 사용
 - [ ] 탭 바 컨트롤러 구성
 - [ ] 스토리보드 분리
 - [ ] 스택 뷰 UI 사용

`도전과제`
 - [ ] 선택된 탭에 따라 다른 효과 부여

`심화과제`
- [ ] 화면 전환 시 적절한 화면 전환 방식 구현하기

## 🌱 PR Point
- 스토리보드를 나누는 기준에 대한 고민을 해보았습니다
메인 스토리보드는 아직 분리를 안해둔 상태인데, 화면가입 화면(1,2)는 같은 스토리보드에 넣는게 좋을지 아니면 매화면마다 스토리보드를 나눠야하는지..!
- 스토리보드를 분리하려면 상수로 선언하는 과정이 반드시 필요한지 ,다른 분들은 스토리보드 분리를 어떻게 했는지 궁금해요 🧐

## 📸 스크린샷
|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 오토레이아웃 설정 |  ![Simulator Screen Recording - iPhone 13 mini - 2022-04-21 at 23 09 59](https://user-images.githubusercontent.com/54045865/164476703-6a47d248-f8d7-4dae-86c5-848feb57b3b7.gif) |
| 탭바 구현 | ![Simulator Screen Recording - iPhone 13 mini - 2022-04-21 at 23 11 20](https://user-images.githubusercontent.com/54045865/164476963-e696b393-d404-4fd7-9f7d-c6785a220c36.gif) |

## 📮 관련 이슈

- Resolved: #4

2022-04-24 06:40 UTC, Jihyun247 commented
> 스토리보드를 나누는 기준에 대한 고민을 해보았습니다
메인 스토리보드는 아직 분리를 안해둔 상태인데, 화면가입 화면(1,2)는 같은 스토리보드에 넣는게 좋을지 아니면 매화면마다 스토리보드를 나눠야하는지..!

저라면 가입 화면(1,2)는 비슷한 UI, 비슷한 로직으로 구성되어서 같은 스토리보드에 넣을 것 같아요 !

2022-04-24 13:11 UTC, jane1choi requested changes
PR포인트에 남긴 질문에 대한 답변을 좀 해보자면,,
일단 스토리보드를 나누는 이유에 대해서 정확히 파악하는게 중요할 것 같은데요!
스토리보드를 나누어서 쓰는 이유는
~~~
1. 한 스토리보드 파일에 ViewController가 많아지면 빌드 속도가 느려진다는 문제점
2. 한 스토리보드 파일을 공동 협업자와 내가 동시에 수정할 경우 Merge 시 conflict가 발생한다는 문제점
~~~
이렇게 두개로 정리 할 수 있을 것 같습니다!

만약에 개인 프로젝트라면, 저도 지현이가 남겨주신 코멘트 처럼 회원가입 1,2 화면 정도는 같은 기능에 대한 뷰이니 한 파일에 넣을 것 같아요!
하지만, 만약에 프로젝트에서 회원가입 1화면을 소진이가 맡고, 2화면을 다른 공동 협업자가 맡는 경우에
스토리보드 파일에서 날 수 있는 충돌을 방지하기 위해서 분리할 것 같습니다! 
실제로 1 Storyboad 1 ViewController를 컨벤션으로 가져가는 경우도 있는데, 협업 시에 논의해보면 좋을 문제라고 생각합니다!
요부분 참고만 해주고, 지금은 소진이만 작업하는 과제이니 원하는 대로 해도 무방할 것 같아요😊😊
2차 과제도 넘 수고했고! 리뷰 참고해서 리팩토링까지 해봅시다🔥 수고했어요~!!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/Constants/Const.swift
> +struct Const {
요거는 왜 만들었는지 물어봐도 될까요?? 추후에 사용할 구조체인가요??

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/Constants/Storyboard.swift
> +        }
`identifier`를 선언해두려고 요부분을 만들어둔 것 같은데, 개인적으로 이 코드가 좋은 방법 같지는 않아요!
어떤 의도가 있는지는 잘 모르겠지만, Const라는 구조체 안에 Storyboad 라는 구조체 안에 또 Name이라는 구초체가 있는거니까..!

~~~Swift
struct StoryBoardName {
    static let home = "Home"
    static let search = "Search"
    static let tabBar = "TabBar"
    static let profile = "Profile"
    static let shop = "Shop"
    static let reels = "Reels"
}
~~~
이런식으로 바꿔보는건 어떨까요?
그리고, 스토리보드 파일명은 `HomeStoryBoard.storyboard`와 같이 스토리보드임을 명시해주는 네이밍이 더 좋다고 생각합니다!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/Constants/ViewControllers.swift
> +        }
요부분도 위에 남긴 리뷰와 같이 하나의 구조체 안에다가 합쳐줘도 될 것 같습니다!
~~~Swift
struct identifier {
        static let home = "HomeViewController"
        static let search = "SearchViewController"
        static let profile = "ProfileViewController"
        static let shop = "ShopViewController"
        static let reels = "ReelsViewController"
        static let tabBar = "TabBarController"
    }
~~~

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/Reels/ReelsViewController.swift
> +    */
요렇게 파일 생성하면 디폴트로 생기는 주석은 필요 없는 주석이니 다 지워주면 좋을 것 같아요!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/SuccessViewController.swift
> +        //self.dismiss(animated: true, completion: nil)
요렇게 주석처리 해놓은 부분도 필요없는 코드라면 지워줍시다!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/SuccessViewController.swift
> +        guard let TabBarController = TabBarStoryboard.instantiateViewController(withIdentifier: Const.TabBarController.identifier.tabBar) as? TabBarController
위의 중첩되는 구조체 때문에 identifier 불러와서 사용해줄 때
`withIdentifier: Const.TabBarController.identifier.tabBar`
이렇게 호출 코드가 길어지죠? 
이렇게 호출해주어야 한다면 identifier이름을 `String`타입으로 써주는 것이 오히려 더 깔끔해지는 것 같아요..
구조체 부분 코드 수정해봅시다!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +        self.delegate = self
3주차 세미나에서 `delegate`에 대해서 배워서 이제 알겠지만..!
delegate는 대리자 위임 메서드라고 할 수 있는데요,
`self.delegate = self`
라는 코드는 나의 대리자를 다시 나로 지정한다..? 정도로 해석할 수 있을 것 같은데,, 
나에 대한 처리를 담당하는 사람은 이미 나니까 불필요한 코드라는 것이 느껴지나요?
요부분 지워줍시다~!

2022-04-24 13:11 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +        }
도전과제까지 깔끔하게 잘 처리했네요!! 굿굿👍🏻👍🏻

2022-04-26 12:45 UTC, 513sojin commented on SOPT30th-Assignment/Instagram/Instagram/Constants/Const.swift
> +struct Const {
@jane1choi 구글링해서 찾아봤을 때 따라하라는 대로 따라하느라 만든 파일인데 사용되지 않아서 삭제해보려 합니다 ..😇

2022-04-26 12:45 UTC, 513sojin commented on SOPT30th-Assignment/Instagram/Instagram/SuccessViewController.swift
> +        guard let TabBarController = TabBarStoryboard.instantiateViewController(withIdentifier: Const.TabBarController.identifier.tabBar) as? TabBarController
@jane1choi identifier이름을 String 타입으로 써준다는게 어떤 의미인가용 ?!

2022-04-26 12:58 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/SuccessViewController.swift
> +        guard let TabBarController = TabBarStoryboard.instantiateViewController(withIdentifier: Const.TabBarController.identifier.tabBar) as? TabBarController
@513sojin 
(withIdentifier: "SecondViewController")
이런 식으로 써주는 것을 StoryBoardID를 그대로 써주는 것을 의미했습니다.

2022-04-26 14:43 UTC, jeongkite commented on SOPT30th-Assignment/Instagram/Instagram/Constants/ViewControllers.swift
> +    }
오옹 근데 이렇게 자주 쓰는 것들 선언해서 쓰는건 너무 좋은 방법 같아요!!!😲👍👍 밑에 은주언니 코멘트도 참고해서 다음에 적용해봐야겠네요!!!

2022-05-01 15:14 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +            title: "",
요거 타이틀 설정 안해줘도 될 것 같아요!

2022-05-01 15:14 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +        itemIndex == 2 ? configureDarkUI() : configureDefaultUI()
굳굳!

2022-05-01 15:21 UTC, 513sojin commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +            title: "",
@jane1choi 타이틀이 필수 파라미터라 넣어달라고 하는데 혹시 타이틀을 설정안해주거나 ""말고도 안보이게 하는 방법을 아시나용..!?

2022-05-01 15:26 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +        let HomeStoryboard = UIStoryboard(name: "Home", bundle: nil)
요거 identifier 따로 빼놓고 쓰고 싶다면,

~~~Swift
struct Identifiers {
    static let HomeStoryBoard = "HomeStoryBoard"
    static let SearchStoryBoard = "SearchStoryBoard"
    static let ReelsStoryBoard = "ReelsStoryBoard"
    static let ProfileStoryBoard = "ProfileStoryBoard"
    static let ShopStoryBoard = "ShopStoryBoard"
}
~~~
새로운 파일하나 만들어서 요렇게 static 으로 선언해두고 
UIStoryboard(name: 파일명.ShopSB, bundle: nil)
이런식으로 자동완성되도록 해서 쓸 수 있습니다!
그리고 스토리보드임을 명시해주는 네이밍이 좋다고 생각해요! 
ex) HomeStoryBoard, HomeSB

2022-05-01 15:31 UTC, jane1choi commented on SOPT30th-Assignment/Instagram/Instagram/TabBar/TabBarController.swift
> +            title: "",
@513sojin 아하 고렇다면 요 리뷰는 무시해주세열,,

2022-05-01 15:38 UTC, merged